#!/bin/bash
module add bio/bowtie2
module add bio/tophat
#bowtie2-build /home/saba/index/rmsk.rRNA.RGSC5.0.rn5.fa /home/saba/index/rmsk.rRNA.RGSC5.0.rn5
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx1.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/BN_LX_1_LV_total_RNA_cDNA_CTTGTA_L007_R1_val_1.fq /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/BN_LX_1_LV_total_RNA_cDNA_CTTGTA_L007_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx2.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/BN_LX_2_LV_total_RNA_cDNA_GTGAAA_L007_R1_val_1.fq /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/BN_LX_2_LV_total_RNA_cDNA_GTGAAA_L007_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx3.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/BN_LX_3_LV_total_RNA_cDNA_CAGATC_L008_R1_val_1.fq /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/BN_LX_3_LV_total_RNA_cDNA_CAGATC_L008_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx4.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/BN_LX_4_LV_total_RNA_cDNA_CCGTCC_L008_R1_val_1.fq /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/BN_LX_4_LV_total_RNA_cDNA_CCGTCC_L008_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR1.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/SHR_H_1_LV_total_RNA_cDNA_GCCAAT_L005_R1_val_1.fq /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/SHR_H_1_LV_total_RNA_cDNA_GCCAAT_L005_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR2.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/SHR_H_2_LV_total_RNA_cDNA_ACAGTG_L005_R1_val_1.fq /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/SHR_H_2_LV_total_RNA_cDNA_ACAGTG_L005_R2_val_2.fq
#tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR3.rmsk.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/SHR_H_3_LV_total_RNA_cDNA_CGATGT_L006_R1_val_1.fq /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/SHR_H_3_LV_total_RNA_cDNA_CGATGT_L006_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR4.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/SHR_H_4_LV_total_RNA_cDNA_TGACCA_L006_R1_val_1.fq /home/data/saba/BNLx.SHR.Heart.totalRNA/trimmedReads/SHR_H_4_LV_total_RNA_cDNA_TGACCA_L006_R2_val_2.fq
