#!/bin/bash
samtools view -c -L /home/saba/source/ensemblAndHeartRecon.allExons.RGSC5.0.rn5.bed /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR1.heart.unique.bam | awk -v sample="SHR1" '{print sample,"reconAndEnsembl",$0}' > cntByAnno.heart.02Aug14.txt
samtools view -c -L /home/saba/source/ensemblAndHeartRecon.allExons.RGSC5.0.rn5.bed /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR2.heart.unique.bam | awk -v sample="SHR2" '{print sample,"reconAndEnsembl",$0}' >> cntByAnno.heart.02Aug14.txt
samtools view -c -L /home/saba/source/ensemblAndHeartRecon.allExons.RGSC5.0.rn5.bed /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR3.heart.unique.bam | awk -v sample="SHR3" '{print sample,"reconAndEnsembl",$0}' >> cntByAnno.heart.02Aug14.txt
samtools view -c -L /home/saba/source/ensemblAndHeartRecon.allExons.RGSC5.0.rn5.bed /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR4.heart.unique.bam | awk -v sample="SHR4" '{print sample,"reconAndEnsembl",$0}' >> cntByAnno.heart.02Aug14.txt
samtools view -c -L /home/saba/source/ensemblAndHeartRecon.allExons.RGSC5.0.rn5.bed /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx1.heart.unique.bam | awk -v sample="BNLx1" '{print sample,"reconAndEnsembl",$0}' >> cntByAnno.heart.02Aug14.txt
samtools view -c -L /home/saba/source/ensemblAndHeartRecon.allExons.RGSC5.0.rn5.bed /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx2.heart.unique.bam | awk -v sample="BNLx2" '{print sample,"reconAndEnsembl",$0}' >> cntByAnno.heart.02Aug14.txt
samtools view -c -L /home/saba/source/ensemblAndHeartRecon.allExons.RGSC5.0.rn5.bed /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx3.heart.unique.bam | awk -v sample="BNLx3" '{print sample,"reconAndEnsembl",$0}' >> cntByAnno.heart.02Aug14.txt
samtools view -c -L /home/saba/source/ensemblAndHeartRecon.allExons.RGSC5.0.rn5.bed /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx4.heart.unique.bam | awk -v sample="BNLx4" '{print sample,"reconAndEnsembl",$0}' >> cntByAnno.heart.02Aug14.txt
