#!/bin/bash
module add bio/bowtie2
module add bio/tophat
tophat2 --library-type fr-firststrand -o /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx1 -p 16 /storage/saba/index/BNLx_rn5_wSpikesAndM /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx1.rRNA/unmapped.end1.fq /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx1.rRNA/unmapped.end2.fq
tophat2 --library-type fr-firststrand -o /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx2 -p 16 /storage/saba/index/BNLx_rn5_wSpikesAndM /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx2.rRNA/unmapped.end1.fq /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx2.rRNA/unmapped.end2.fq
tophat2 --library-type fr-firststrand -o /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx3 -p 16 /storage/saba/index/BNLx_rn5_wSpikesAndM /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx3.rRNA/unmapped.end1.fq /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx3.rRNA/unmapped.end2.fq
tophat2 --library-type fr-firststrand -o /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx4 -p 16 /storage/saba/index/BNLx_rn5_wSpikesAndM /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx4.rRNA/unmapped.end1.fq /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/BNLx4.rRNA/unmapped.end2.fq
#tophat2 --library-type fr-firststrand -o /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR1 -p 16 /storage/saba/index/SHR_rn5_wSpikesAndM /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR1.rRNA/unmapped.end1.fq /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR1.rRNA/unmapped.end2.fq
#tophat2 --library-type fr-firststrand -o /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR2 -p 16 /storage/saba/index/SHR_rn5_wSpikesAndM /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR2.rRNA/unmapped.end1.fq /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR2.rRNA/unmapped.end2.fq 
#tophat2 --library-type fr-firststrand -o /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR3 -p 16 /storage/saba/index/SHR_rn5_wSpikesAndM /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR3.rRNA/unmapped.end1.fq /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR3.rRNA/unmapped.end2.fq 
#tophat2 --library-type fr-firststrand -o /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR4 -p 16 /storage/saba/index/SHR_rn5_wSpikesAndM /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR4.rRNA/unmapped.end1.fq /storage/saba/BNLx.SHR.Heart.totalRNA/alignedReads/SHR4.rRNA/unmapped.end2.fq 
