#!/bin/bash
module load bio/sailfish
sailfish index -t /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.11Jun14.FINAL.fa -k 20 -p 5 -o /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.11Jun14.FINAL
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.11Jun14.FINAL -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS1.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS1.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.FINAL/ILS1
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.11Jun14.FINAL -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS2.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS2.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.FINAL/ILS2
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.11Jun14.FINAL -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS3.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS3.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.FINAL/ILS3
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.11Jun14.FINAL -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS1.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS1.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.FINAL/ISS1
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.11Jun14.FINAL -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS2.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS2.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.FINAL/ISS2
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.11Jun14.FINAL -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS3.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS3.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.FINAL/ISS3
