#!/bin/bash
module load bio/sailfish
sailfish index -t /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.05Jun14.v2.fa -k 20 -p 5 -o /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.05Jun14.v2
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.05Jun14.v2 -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS1.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS1.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.v2/ILS1
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.05Jun14.v2 -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS2.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS2.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.v2/ILS2
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.05Jun14.v2 -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS3.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ILS3.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.v2/ILS3
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.05Jun14.v2 -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS1.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS1.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.v2/ISS1
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.05Jun14.v2 -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS2.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS2.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.v2/ISS2
sailfish quant -i /home/saba/ILS.ISS.Brain.totalRNA/reconstruction/transcripts.05Jun14.v2 -l "T=PE:O=><:S=AS" -1 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS3.R1.fq -2 /home/saba/ILS.ISS.Brain.totalRNA/trimmedReads/ISS3.R2.fq -p 10 -o /home/saba/ILS.ISS.Brain.totalRNA/quantification/sailFish.v2/ISS3
