By Sample Summary Of RNA-Seq Data
========================================================

Male Rats From Michal Pravenec:
-----------------------

```{r,echo=FALSE}
rm(list=ls())
options(stringsAsFactors=FALSE)
setwd("~/Documents/NextGenSeq")

strains = read.table(file="sampleInfo/pravenecStrains.txt",sep="\t",header=FALSE)
tissues = c("brain","heart","liver","brown adipose")
numSamples = 4

malesPravenec = data.frame(strain=rep(strains$V1,each=4),sampleNum=rep(c(1:4),nrow(strains)))
malesPravenec$sample = paste(gsub("/Cub","",gsub("/Ola","",gsub("-","",malesPravenec$strain,fixed=TRUE),fixed=TRUE),fixed=TRUE),malesPravenec$sampleNum,sep="_")

malesPravenec$brain = "in freezer"
malesPravenec$heart = "in freezer"
malesPravenec$liver = "in freezer"
malesPravenec$bat = "in freezer"

##  Parental Heart Analysis - 4/14
malesPravenec$heart[malesPravenec$strain %in% c("BN-Lx/Cub","SHR/Ola")] = "total RNA sequenced (02Jun14); small RNA sequenced (19May14)"

##  Batch 1 RI Brains - 9/14
batch1 = paste(rep(c("HXB27","HXB7","HXB25","HXB17","HXB2","HXB13","BXH12","SHR"),each=2),rep(c(1:2),8),sep="_")
malesPravenec$brain[malesPravenec$sample %in% batch1] = "total RNA sequenced (05Sep14); small RNA sequenced (21Jul14)"
              
##  Batch 2 RI Brains - 9/14             
batch2 = c(paste(c("HXB1","HXB3","HXB4","HXB5","HXB10","HXB15","HXB18","HXB20","HXB21","HXB22","HXB23","HXB24","HXB29","HXB31","BXH2"),"_1",sep=""))
malesPravenec$brain[malesPravenec$sample %in% batch2] = "total RNA sequenced (24Sep14); small RNA sequenced (23Sep14)"
malesPravenec$brain[malesPravenec$sample=="SHR_1"] = "total RNA sequenced (05Sep14); small RNA sequenced (21Jul14); REPLICATE (same extraction/different library prep) - total RNA sequenced (24Sep14) and small RNA sequenced (23Sep14)"

##  Batch 3 RI Brains - 9/25
batch3 = c("BXH3_1","BXH3_2","BXH5_1","BXH6_1","BXH6_2","BXH8_1","BXH9_1","BXH9_2","BXH10_1","BXH10_2","BXH11_1","BXH11_2","BXH13_1","BNLx_1","BNLx_2")
malesPravenec$brain[malesPravenec$sample %in% batch3] = "total RNA sequenced (20Nov14)"
malesPravenec$brain[malesPravenec$sample=="SHR_1"] = paste(malesPravenec$brain[malesPravenec$sample=="SHR_1"],"; REPLICATE2 total RNA sequenced (20Nov14)",sep="")
```


```{r,results="asis",echo=FALSE}
#make table pretty for printing
forPrint = malesPravenec[,c("strain","sample","brain","heart","liver","bat")]
colnames(forPrint) = c("Strain","Sample ID","Brain","Left Ventricle","Liver","Brown Adipose Tissue")
kable(forPrint,align=rep("c",ncol(forPrint)))
```

### By Tissue Summary

```{r,echo=FALSE}
summary = c()
for(tissue in c("brain","liver","heart","bat")){
  numSamples = aggregate(malesPravenec[,tissue],by=list(malesPravenec$strain),function(a) sum(grepl("total RNA sequenced",a)))
  numSamples.small = aggregate(malesPravenec[,tissue],by=list(malesPravenec$strain),function(a) sum(grepl("small RNA sequenced",a)))
  summary = rbind(summary,data.frame(tissue=tissue,avg.long=mean(numSamples$x),atLeast1.long=sum(numSamples$x>0),all4.long = sum(numSamples$x==4),avg.small=mean(numSamples.small$x),atLeast1.small=sum(numSamples.small$x>0),all4.small = sum(numSamples.small$x==4)))
}

```

```{r,results="asis",echo=FALSE}
#make table pretty for printing
forPrint2 = summary
forPrint2$avg.long = sprintf("%0.2f",round(forPrint2$avg.long,2))
forPrint2$avg.small = sprintf("%0.2f",round(forPrint2$avg.small,2))
colnames(forPrint2) = c("Tissue","Average Number of Samples Per Strain (total RNA)","Number of Strains with At Least 1 Sample (total RNA)","Number of Strains with All 4 Samples Per Strain (total RNA)","Average Number of Samples Per Strain (small RNA)","Number of Strains with At Least 1 Sample (small RNA)","Number of Strains with All 4 Samples Per Strain (small RNA)")
kable(forPrint2,align=rep("c",ncol(forPrint2)))
```





