---
title: "Liver Transcriptome Reconstruction"
author: "Laura Saba"
date: "September 20, 2015"
output: html_document
---

rRNA-Depleted Total RNA Reconstruction
--------------------

###1.  Strain-Specific Transcriptome Reconstruction (Ensembl-Guided) - 

```
qsub -q smp -N BNLx.liver /storage/saba/BNLx.SHR.Liver.totalRNA/programs/reconBNLx.liver.sh
qsub -q smp -N SHR.liver /storage/saba/BNLx.SHR.Liver.totalRNA/programs/reconSHR.liver.sh
```

###2. Create GTF file for viewing at UCSC
```{r,echo=FALSE}
rm(list=ls())
options(stringsAsFactors=FALSE)
setwd("/Volumes/saba/BNLx.SHR/RNA-Seq.Liver/reconstruction")
printNow=FALSE

#######################
##  local functions  ##
#######################

# format GTF files to include transcript ids, gene ids, and fpkm values
gtfFormat = function(data,FPKM=TRUE){
  data$transcript_id = unlist(lapply(strsplit(data$V9,split=";",fixed=TRUE),function(a) gsub(" transcript_id ","",a[grep("transcript",a)]))) 
  data$gene_id = unlist(lapply(strsplit(data$V9,split=";",fixed=TRUE),function(a) gsub("gene_id ","",a[grep("gene",a)]))) 
  if(FPKM) data$fpkm = as.numeric(unlist(lapply(strsplit(data$V9,split=";",fixed=TRUE),function(a) gsub(" FPKM ","",a[grep("FPKM",a)]))))
  return(data)
}
```


```{r}
shr = read.table(file = "SHR.Liver.total.rn6.ensemblGuided/transcripts.gtf",sep="\t",header=FALSE)
shr = gtfFormat(shr)
shr.ucsc = shr[shr$V1 %in% c(1:20,"X","Y"),]
shr.ucsc = shr.ucsc[shr.ucsc$fpkm>0,]
shr.ucsc$V1 = paste("chr",shr.ucsc$V1,sep="")
shr.ucsc$V9 = paste('gene_id "',shr.ucsc$gene_id,'"; transcript_id "',shr.ucsc$transcript_id,'";',sep="")
write.table(shr.ucsc[,paste("V",1:9,sep="")],file = "SHR.Liver.total.rn6.ensemblGuided/transcripts.ucsc.gtf",sep="\t",row.names=FALSE,col.names=FALSE,quote=FALSE)

bnlx = read.table(file = "BNLx.Liver.total.rn6.ensemblGuided/transcripts.gtf",sep="\t",header=FALSE)
bnlx = gtfFormat(bnlx)
bnlx.ucsc = bnlx[bnlx$V1 %in% c(1:20,"X","Y"),]
bnlx.ucsc = bnlx.ucsc[bnlx.ucsc$fpkm>0,]
bnlx.ucsc$V1 = paste("chr",bnlx.ucsc$V1,sep="")
bnlx.ucsc$V9 = paste('gene_id "',bnlx.ucsc$gene_id,'"; transcript_id "',bnlx.ucsc$transcript_id,'";',sep="")
write.table(bnlx.ucsc[,paste("V",1:9,sep="")],file = "BNLx.Liver.total.rn6.ensemblGuided/transcripts.ucsc.gtf",sep="\t",row.names=FALSE,col.names=FALSE,quote=FALSE)
```
