#!/bin/bash
module add bio/bowtie2
module add bio/tophat
#bowtie2-build /home/saba/index/rmsk.rRNA.RGSC5.0.rn5.fa /home/saba/index/rmsk.rRNA.RGSC5.0.rn5
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx1.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B1_CAGATC_L001_R1_val_1.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B1_CAGATC_L002_R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B1_CAGATC_L001_R2_val_2.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B1_CAGATC_L002_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx2.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B2_ATGTCA_L001_R1_val_1.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B2_ATGTCA_L002_R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B2_ATGTCA_L001_R2_val_2.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B2_ATGTCA_L002_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx3.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B3_CTTGTA_L001_R1_val_1.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B3_CTTGTA_L002_R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B3_CTTGTA_L001_R2_val_2.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B3_CTTGTA_L002_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx4.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B4_CCGTCC_L001_R1_val_1.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B4_CCGTCC_L002_R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B4_CCGTCC_L001_R2_val_2.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/B4_CCGTCC_L002_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR1.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S1_CGATGT_L001_R1_val_1.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S1_CGATGT_L002_R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S1_CGATGT_L001_R2_val_2.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S1_CGATGT_L002_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR2.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S2_ACAGTG_L001_R1_val_1.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S2_ACAGTG_L002_R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S2_ACAGTG_L001_R2_val_2.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S2_ACAGTG_L002_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR3.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S3_GCCAAT_L001_R1_val_1.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S3_GCCAAT_L002_R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S3_GCCAAT_L001_R2_val_2.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S3_GCCAAT_L002_R2_val_2.fq
tophat2 -g 2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR4.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S4_TGACCA_L001_R1_val_1.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S4_TGACCA_L002_R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S4_TGACCA_L001_R2_val_2.fq,/home/data/saba/BNLx.SHR.Brain.Females.totalRNA/trimmedReads/S4_TGACCA_L002_R2_val_2.fq
