#!/bin/bash
module add bio/sailfish
sailfish quant -i /storage/saba/index/ensGene.SHR.wSpikes.18Jun14 -l "T=PE:O=><:S=AS" -1 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR1.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR1.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.Females.totalRNA/quantitation/SHR1.ensembl
sailfish quant -i /storage/saba/index/ensGene.SHR.wSpikes.18Jun14 -l "T=PE:O=><:S=AS" -1 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR2.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR2.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.Females.totalRNA/quantitation/SHR2.ensembl
sailfish quant -i /storage/saba/index/ensGene.SHR.wSpikes.18Jun14 -l "T=PE:O=><:S=AS" -1 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR3.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR3.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.Females.totalRNA/quantitation/SHR3.ensembl
sailfish quant -i /storage/saba/index/ensGene.SHR.wSpikes.18Jun14 -l "T=PE:O=><:S=AS" -1 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR4.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR4.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.Females.totalRNA/quantitation/SHR4.ensembl
sailfish quant -i /storage/saba/index/ensGene.BNLx.wSpikes.18Jun14 -l "T=PE:O=><:S=AS" -1 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx1.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx1.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.Females.totalRNA/quantitation/BNLx1.ensembl
sailfish quant -i /storage/saba/index/ensGene.BNLx.wSpikes.18Jun14 -l "T=PE:O=><:S=AS" -1 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx2.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx2.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.Females.totalRNA/quantitation/BNLx2.ensembl
sailfish quant -i /storage/saba/index/ensGene.BNLx.wSpikes.18Jun14 -l "T=PE:O=><:S=AS" -1 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx3.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx3.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.Females.totalRNA/quantitation/BNLx3.ensembl
sailfish quant -i /storage/saba/index/ensGene.BNLx.wSpikes.18Jun14 -l "T=PE:O=><:S=AS" -1 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx4.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx4.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.Females.totalRNA/quantitation/BNLx4.ensembl
