#!/bin/bash
module add bio/bowtie2
module add bio/tophat
tophat2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx1 -p 16 /home/saba/index/BNLx_rn5_wSpikesAndM /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx1.rRNA/unmapped.end1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx1.rRNA/unmapped.end2.fq
tophat2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx2 -p 16 /home/saba/index/BNLx_rn5_wSpikesAndM /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx2.rRNA/unmapped.end1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx2.rRNA/unmapped.end2.fq
tophat2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx3 -p 16 /home/saba/index/BNLx_rn5_wSpikesAndM /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx3.rRNA/unmapped.end1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx3.rRNA/unmapped.end2.fq
tophat2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx4 -p 16 /home/saba/index/BNLx_rn5_wSpikesAndM /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx4.rRNA/unmapped.end1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/BNLx4.rRNA/unmapped.end2.fq
tophat2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR1 -p 16 /home/saba/index/SHR_rn5_wSpikesAndM /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR1.rRNA/unmapped.end1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR1.rRNA/unmapped.end2.fq
tophat2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR2 -p 16 /home/saba/index/SHR_rn5_wSpikesAndM /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR2.rRNA/unmapped.end1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR2.rRNA/unmapped.end2.fq 
tophat2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR3 -p 16 /home/saba/index/SHR_rn5_wSpikesAndM /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR3.rRNA/unmapped.end1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR3.rRNA/unmapped.end2.fq 
tophat2 --library-type fr-firststrand -o /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR4 -p 16 /home/saba/index/SHR_rn5_wSpikesAndM /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR4.rRNA/unmapped.end1.fq /home/data/saba/BNLx.SHR.Brain.Females.totalRNA/alignedReads/SHR4.rRNA/unmapped.end2.fq 
