#!/bin/bash
module add bio/bowtie2
module add bio/tophat
tophat2 -g 2 --library-type fr-unstranded -o /home/data/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx1.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/BNLx1.R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/BNLx1.R2_val_2.fq
tophat2 -g 2 --library-type fr-unstranded -o /home/data/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx2.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/BNLx2.R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/BNLx2.R2_val_2.fq
tophat2 -g 2 --library-type fr-unstranded -o /home/data/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx3.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/BNLx3.R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/BNLx3.R2_val_2.fq
tophat2 -g 2 --library-type fr-unstranded -o /home/data/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR1.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/SHR1.R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/SHR1.R2_val_2.fq
tophat2 -g 2 --library-type fr-unstranded -o /home/data/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR2.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/SHR2.R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/SHR2.R2_val_2.fq
tophat2 -g 2 --library-type fr-unstranded -o /home/data/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR3.rRNA -p 16 /home/saba/index/rmsk.rRNA.RGSC5.0.rn5 /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/SHR3.R1_val_1.fq /home/data/saba/BNLx.SHR.Brain.totalRNA/trimmedReads/SHR3.R2_val_2.fq
