#!/bin/bash
#PBS -l nodes=smp-3-2
module add bio/sailfish
sailfish quant -i /storage/saba/index/ensGene.SHR.wSpikes.18Jun14 -l "T=PE:O=><:S=U" -1 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR1.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR1.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.totalRNA/quantitation/SHR1.ensembl
sailfish quant -i /storage/saba/index/ensGene.SHR.wSpikes.18Jun14 -l "T=PE:O=><:S=U" -1 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR2.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR2.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.totalRNA/quantitation/SHR2.ensembl
sailfish quant -i /storage/saba/index/ensGene.SHR.wSpikes.18Jun14 -l "T=PE:O=><:S=U" -1 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR3.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/SHR3.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.totalRNA/quantitation/SHR3.ensembl
sailfish quant -i /storage/saba/index/ensGene.BNLx.wSpikes.18Jun14 -l "T=PE:O=><:S=U" -1 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx1.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx1.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.totalRNA/quantitation/BNLx1.ensembl
sailfish quant -i /storage/saba/index/ensGene.BNLx.wSpikes.18Jun14 -l "T=PE:O=><:S=U" -1 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx2.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx2.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.totalRNA/quantitation/BNLx2.ensembl
sailfish quant -i /storage/saba/index/ensGene.BNLx.wSpikes.18Jun14 -l "T=PE:O=><:S=U" -1 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx3.rRNA/unmapped.end1.fq -2 /storage/saba/BNLx.SHR.Brain.totalRNA/alignedReads/BNLx3.rRNA/unmapped.end2.fq -p 5 -o /storage/saba/BNLx.SHR.Brain.totalRNA/quantitation/BNLx3.ensembl
